import { C4DiagramData } from '../types';

export const C4_DIAGRAMS: Record<string, C4DiagramData> = {
  level1: {
    level: 'Level 1: System Context',
    title: 'light-weight-agentic-engineering — System Context Diagram',
    description: 'Depicts high-level external actors, users, enterprise core systems, and external SaaS platforms interacting with the light-weight-agentic-engineering boundary.',
    elements: [
      {
        id: 'actor-user',
        name: 'Enterprise Discovery Visitors',
        type: 'Person',
        description: 'Users exploring architectural solutions, technical specifications, and AI capabilities.'
      },
      {
        id: 'actor-engineer',
        name: 'Enterprise Engineers & Architects',
        type: 'Person',
        description: 'Software engineers requesting feature PR drafts, architecture reviews, and production release sign-offs.'
      },
      {
        id: 'actor-release-mgr',
        name: 'Release Managers & SREs',
        type: 'Person',
        description: 'Operations leads managing gated rollouts, incident runbooks, and audit verifications.'
      },
      {
        id: 'system-agentic-platform',
        name: 'light-weight-agentic-engineering Platform',
        type: 'System',
        description: 'Autonomous multi-agent system orchestrating LLM inference, MCP tool calls, durable Temporal workflows, and knowledge retrieval.',
        technology: 'Local M2 Metal / Kubernetes'
      },
      {
        id: 'system-github',
        name: 'GitHub / GitLab Enterprise',
        type: 'System',
        description: 'Source control hosting monorepos, pull requests, branch protection, and CI status checks.',
        technology: 'SaaS / Enterprise Server'
      },
      {
        id: 'system-jira',
        name: 'Atlassian Jira / Confluence',
        type: 'System',
        description: 'Issue tracking for engineering sprints, epics, bug tickets, and architecture documentation.',
        technology: 'REST API'
      },
      {
        id: 'system-crm',
        name: 'Salesforce / HubSpot CRM',
        type: 'System',
        description: 'Enterprise customer relationship management for qualified leads generated by AI concierge.',
        technology: 'REST / GraphQL'
      },
      {
        id: 'system-cms',
        name: 'Strapi / Contentful CMS',
        type: 'System',
        description: 'Headless CMS powering web content, service catalogs, and architectural guidelines.',
        technology: 'Headless API'
      }
    ],
    relationships: [
      { sourceId: 'actor-user', targetId: 'system-agentic-platform', description: 'Explores AI solutions & concierge', protocol: 'HTTPS / Web' },
      { sourceId: 'actor-engineer', targetId: 'system-agentic-platform', description: 'Triggers PR drafts, architecture reviews & evals', protocol: 'HTTPS / Portal' },
      { sourceId: 'actor-release-mgr', targetId: 'system-agentic-platform', description: 'Inspects release risk & signs off promotion gates', protocol: 'HTTPS / HITL' },
      { sourceId: 'system-agentic-platform', targetId: 'system-github', description: 'Queries repo context & opens Draft PRs via MCP', protocol: 'GitHub REST / MCP' },
      { sourceId: 'system-agentic-platform', targetId: 'system-jira', description: 'Reads tickets & updates acceptance criteria', protocol: 'Jira API / MCP' },
      { sourceId: 'system-agentic-platform', targetId: 'system-crm', description: 'Captures consultation leads under draft action class', protocol: 'CRM Webhooks' },
      { sourceId: 'system-agentic-platform', targetId: 'system-cms', description: 'Ingests marketing content & service taxonomy', protocol: 'GraphQL Ingestion' }
    ]
  },

  level2: {
    level: 'Level 2: Container (6 Planes)',
    title: 'light-weight-agentic-engineering 6-Plane Enterprise Container Architecture',
    description: 'Shows the 6 decoupled architectural planes, their primary services/containers, protocols, and persistent datastores.',
    elements: [
      {
        id: 'c-exp',
        name: '1. Experience Plane',
        type: 'Container',
        plane: 'Experience',
        technology: 'Next.js 14, TypeScript, Tailwind, Design System',
        description: 'Houses Public Web, Engineering Portal, Admin Console, and Docs Portal.'
      },
      {
        id: 'c-wf',
        name: '2. Workflow Plane',
        type: 'Container',
        plane: 'Workflow',
        technology: 'Temporal Server + Go/Python Workers',
        description: 'Durable state machine, Human-in-the-Loop approvals, task retry queues, and release orchestrator.'
      },
      {
        id: 'c-agent',
        name: '3. Agent Control Plane',
        type: 'Container',
        plane: 'Agent Control',
        technology: 'FastAPI, LangGraph, Ollama Metal / vLLM',
        description: 'Houses Agent Gateway, LLM Gateway, Memory Service, Context Service, and Prompt Registry.'
      },
      {
        id: 'c-know',
        name: '4. Knowledge Plane',
        type: 'Container',
        plane: 'Knowledge',
        technology: 'PostgreSQL + pgvector, OpenSearch, FastAPI',
        description: 'Ingestion, indexing, hybrid retrieval (cosine + BM25), and citation provenance service.'
      },
      {
        id: 'c-tool',
        name: '5. Tool Integration Plane',
        type: 'Container',
        plane: 'Tool Integration',
        technology: 'MCP Gateway, Execution Broker, Secrets Broker',
        description: 'Mediates all external tool interactions with sandboxed adapters (Git, Jira, CRM, Scanners).'
      },
      {
        id: 'c-gov',
        name: '6. Operations & Governance Plane',
        type: 'Container',
        plane: 'Operations & Governance',
        technology: 'Policy Engine (OPA), Audit Log, OTEL, FinOps',
        description: 'Enforces Zero-Trust policy rules, audit trails, telemetry, token budgeting, and multi-tenancy.'
      },
      {
        id: 'db-postgres',
        name: 'PostgreSQL + pgvector',
        type: 'Database',
        technology: 'Postgres 16 + HNSW Index',
        description: 'Stores LangGraph checkpoints, Temporal history, embeddings (1536-dim), and audit entries.'
      },
      {
        id: 'db-redis',
        name: 'Redis Cache & Bus',
        type: 'Queue',
        technology: 'Redis 7 Alpine',
        description: 'Session state, rate limiting, LLM prompt cache, and async pub/sub channels.'
      }
    ],
    relationships: [
      { sourceId: 'c-exp', targetId: 'c-agent', description: 'Dispatches user queries & agent tasks', protocol: 'HTTP/2 gRPC' },
      { sourceId: 'c-exp', targetId: 'c-wf', description: 'Starts PR drafting & release workflows', protocol: 'Temporal gRPC' },
      { sourceId: 'c-agent', targetId: 'c-gov', description: 'Validates agent action permissions & policies', protocol: 'OPA Policy Check' },
      { sourceId: 'c-agent', targetId: 'c-know', description: 'Retrieves verified domain grounding chunks', protocol: 'Vector Search / JSON' },
      { sourceId: 'c-agent', targetId: 'c-tool', description: 'Dispatches tool calls with strict action class', protocol: 'Model Context Protocol (MCP)' },
      { sourceId: 'c-wf', targetId: 'c-agent', description: 'Invokes coding/release agents in workflow activities', protocol: 'Temporal Activity SDK' },
      { sourceId: 'c-tool', targetId: 'c-gov', description: 'Audits tool executions & verifies secrets access', protocol: 'Audit Streaming' },
      { sourceId: 'c-agent', targetId: 'db-postgres', description: 'Persists LangGraph thread checkpoints', protocol: 'asyncpg' },
      { sourceId: 'c-know', targetId: 'db-postgres', description: 'Performs vector cosine distance queries', protocol: 'pgvector HNSW' },
      { sourceId: 'c-agent', targetId: 'db-redis', description: 'Caches LLM completions & session tokens', protocol: 'RESP3' }
    ]
  },

  level3: {
    level: 'Level 3: Component (Agent & MCP)',
    title: 'Component Deep Dive — Agent Control & Tool Integration Planes',
    description: 'Detailed view of the Agent Gateway LangGraph cyclic state machine and the Zero-Trust Tool Brokerage system.',
    elements: [
      {
        id: 'comp-agent-gw',
        name: 'Agent Gateway API',
        type: 'Component',
        plane: 'Agent Control',
        technology: 'FastAPI / Asyncio',
        description: 'Receives AgentTask requests, initializes LangGraph state graphs, and manages execution lifecycle.'
      },
      {
        id: 'comp-langgraph',
        name: 'LangGraph Cyclic Engine',
        type: 'Component',
        plane: 'Agent Control',
        technology: 'LangGraph 0.2.x',
        description: 'Cyclic graph nodes: validate_intent -> retrieve_knowledge -> llm_synthesis -> eval_gate -> tool_dispatch.'
      },
      {
        id: 'comp-llm-router',
        name: 'LLM Gateway Router',
        type: 'Component',
        plane: 'Agent Control',
        technology: 'httpx + Ollama API',
        description: 'Routes prompts to local M2 models (llama3.2:3b, qwen2.5-coder) or cloud fallbacks with prompt sanitization.'
      },
      {
        id: 'comp-eval-service',
        name: 'Evaluation & Guardrails Gate',
        type: 'Component',
        plane: 'Agent Control',
        technology: 'Pydantic + RAGAS',
        description: 'Scores output groundedness (must be >0.85), toxicity, and ensures zero secrets are in output.'
      },
      {
        id: 'comp-mcp-gw',
        name: 'MCP Gateway Controller',
        type: 'Component',
        plane: 'Tool Integration',
        technology: 'FastAPI / MCP SDK',
        description: 'Validates MCP JSON-RPC protocol messages and routes to appropriate adapter.'
      },
      {
        id: 'comp-sec-broker',
        name: 'Secrets Broker',
        type: 'Component',
        plane: 'Tool Integration',
        technology: 'Vault / Ephemeral Tokens',
        description: 'Injects Just-In-Time (JIT) credentials into adapters out-of-band. Agents NEVER touch raw tokens.'
      },
      {
        id: 'comp-exec-broker',
        name: 'Execution Broker & Sandbox',
        type: 'Component',
        plane: 'Tool Integration',
        technology: 'Async Worker / Firecracker',
        description: 'Executes tools in isolated, timeout-guarded workers and redacts sensitive response attributes.'
      },
      {
        id: 'comp-git-adapter',
        name: 'Git Provider Adapter',
        type: 'Component',
        plane: 'Tool Integration',
        technology: 'PyGithub / Git CLI',
        description: 'Handles branch creation, diff generation, and Draft PR opening with commit sign-off.'
      }
    ],
    relationships: [
      { sourceId: 'comp-agent-gw', targetId: 'comp-langgraph', description: 'Instantiates StateGraph for task', protocol: 'In-process Graph' },
      { sourceId: 'comp-langgraph', targetId: 'comp-llm-router', description: 'Calls synthesis step with model route', protocol: 'POST /v1/chat/completions' },
      { sourceId: 'comp-langgraph', targetId: 'comp-eval-service', description: 'Submits generation for groundedness check', protocol: 'Internal Eval Hook' },
      { sourceId: 'comp-langgraph', targetId: 'comp-mcp-gw', description: 'Dispatches approved tool call', protocol: 'MCP JSON-RPC' },
      { sourceId: 'comp-mcp-gw', targetId: 'comp-sec-broker', description: 'Requests scoped ephemeral credential', protocol: 'mTLS' },
      { sourceId: 'comp-mcp-gw', targetId: 'comp-exec-broker', description: 'Delegates execution with actionClass constraint', protocol: 'Async Task' },
      { sourceId: 'comp-exec-broker', targetId: 'comp-git-adapter', description: 'Invokes git branch/PR operations', protocol: 'Adapter Call' }
    ]
  },

  level4: {
    level: 'Level 4: Code & Deployment (M2 Metal vs Cloud K8s)',
    title: 'Deployment Topology — Local Apple Silicon M2 vs Enterprise Cloud Kubernetes',
    description: 'Illustrates how the identical 6-plane codebase runs seamlessly on a local Apple Silicon Mac M2 with Metal GPU acceleration and scales to multi-AZ Kubernetes.',
    elements: [
      {
        id: 'dep-m2-metal',
        name: 'Local Apple Silicon M2 (MacBook Pro / Studio)',
        type: 'Container',
        technology: 'Apple M2 Metal (Unified Memory 16GB-32GB)',
        description: 'Runs Ollama native Metal daemon offloading 100% of weights to GPU cores with zero RAM duplication.'
      },
      {
        id: 'dep-m2-podman',
        name: 'Rootless Podman Machine on M2',
        type: 'Container',
        technology: 'Podman Compose (Profile: Core / Full)',
        description: 'Runs postgres-pgvector, redis, temporal, and lightweight FastAPI services consuming <6.5GB RAM.'
      },
      {
        id: 'dep-k8s-cloud',
        name: 'Enterprise Cloud Kubernetes Cluster',
        type: 'System',
        technology: 'EKS / GKE / OpenShift Multi-AZ',
        description: 'Independently scales each plane across dedicated node pools with HPA and ArgoCD GitOps.'
      },
      {
        id: 'dep-k8s-aurora',
        name: 'Managed Cloud Databases',
        type: 'Database',
        technology: 'Amazon Aurora PostgreSQL + ElastiCache',
        description: 'Multi-AZ read replicas for pgvector similarity searches with automatic failover.'
      }
    ],
    relationships: [
      { sourceId: 'dep-m2-podman', targetId: 'dep-m2-metal', description: 'Connects to Ollama on host.containers.internal:11434', protocol: 'Local Loopback' },
      { sourceId: 'dep-k8s-cloud', targetId: 'dep-k8s-aurora', description: 'Database connections with IAM auth', protocol: 'VPC Peering / TLS' }
    ]
  }
};
